name: Configure Branch Protection

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to protect'
        required: true
        default: 'main'

permissions:
  contents: 'read'
  administration: 'write'

jobs:
  protect-branch:
    runs-on: ubuntu-latest
    name: Protect branch
    steps:
      - name: Configure branch protection via GitHub API
        uses: actions/github-script@v6
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const branch = core.getInput('branch') || 'main';

            core.info(`Setting protection for ${owner}/${repo}@${branch}`);

            try {
              await github.rest.repos.updateBranchProtection({
                owner,
                repo,
                branch,
                required_status_checks: {
                  strict: true,
                  // Require the job name shown in the Checks UI. Adjust if your workflow shows a different name.
                  contexts: ['Build and Test']
                },
                enforce_admins: true,
                required_pull_request_reviews: {
                  dismissal_restrictions: {},
                  dismiss_stale_reviews: true,
                  require_code_owner_reviews: false,
                  required_approving_review_count: 1
                },
                restrictions: null
              });
              core.info('Branch protection updated.');
            } catch (err) {
              core.setFailed(`Failed to update branch protection: ${err.message}`);
            }
